name: artiboost
channels:
  - pytorch
  - nvidia
  - conda-forge
  - fvcore
  - defaults
dependencies:
  - python=3.8.8
  - pip==21.1.0
  - setuptools==52.0.0
  - pytorch==1.8.1
  - cudatoolkit==11.1.1
  - torchvision==0.9.1
  - fvcore==0.1.5.post20220305
  - ipython==7.22.0
  - cython==0.29.22
  - pyembree==0.1.6
